BuildIt-lang/buildit

- src/builder/builder_context.cpp
BuildIt has a weird corner case with its uncommitted_sequence mechanism that an expression can get committed if a variable declaration is seen between the evaluation of the expression and where it is used. This for example can happen in a statement like -
```
a = foo() + b;
```
The evaluation of b can happen before foo(), and foo might declare some variables. This leaves a stray b in the committed code - 
```
b;
a = ... + b;
```
This is usually not bad, but - 
1. It interferes with some pattern matching 
2. Could have unintended side effects. 
The fix is to also scan the committed statements and look for the expression when it is removed from the uncommitted sequence. But this might be unnecessarily slow. So we check if the expression we are trying to delete exists in the …
> Feature to erase expressions that have already been committed

- include/blocks/loop_finder.h
- samples/outputs/sample34
- samples/sample34.cpp
- src/blocks/for_loop_finder.cpp
- src/blocks/loop_finder.cpp
- src/builder/builder_context.cpp
This PR fixes an old bug in BuildIt where sometimes BuildIt would produce code like this - 
```
while (1) {
break;
}
```
if (...) { 
... 
continue;
}
```
This was actually wrong because we were actually peeling out statements (or trimming_from_parents) that still have a continue in them. 
We have now changed to check if the last statement that we are trying to peel (before a break) has a continue. If yes, we don't peel it. This makes BuildIt generate correct code.
Secondly, while detecting for loops, BuildIt always expects the main loop back paths (not from continue) to have an update. This is not necessary, updates could be found from continues too. Or if nothing, one can just create an empty update. We have also changed this similarly.
> Fixed the pesky while(1) break bug

- include/blocks/for_loop_finder.h
- samples/outputs/sample35
- samples/sample35.cpp
- src/blocks/for_loop_finder.cpp
BuildIt had a bug while converting while loops into for loops. For code like this - 
```
dyn_var<int> i = 0; 
for (; i < 100; i = i + 1) {...}
for (i = 0; i < 100; i = i + 1) {...}
```
BuildIt would merge the declaration of `i` into the first for loop. This isn't correct because the variable is used after. 
This change fixes the bug by changing the for_loop_finder pass to check if the variable has more uses after the loop before merging the decl.
> Don;t merge decl before for loops if the variable is used after

- Makefile
- include/blocks/extract_cuda.h
- samples/outputs/sample37
- samples/sample37.cpp
- src/blocks/extract_cuda.cpp
Moved the implementation of the CUDA extraction pass from the easy_graphit and einsum lang repo into the main BuildIt repo. This allows for more reuse and also for use on the online tool.
> Merge CUDA extraction into BuildIt

- include/blocks/var.h
- include/builder/block_type_extractor.h
- samples/outputs/sample32
- samples/sample32.cpp
- src/blocks/block_replacer.cpp
- src/blocks/block_visitor.cpp
- src/blocks/c_code_generator.cpp
- src/blocks/var.cpp
This change allows adding template parameters to named type. `builder::name` now accepts extract template arguments that can be forwarded to the generated type as is by applying type_extractor and printer for each of them. 
This feature makes it easy to implement custom types that inherit from dyn_var<name<T>> to be templated. One of the use cases is in convolutions to implement ImageT.
> Added support for Template parameters for builder::name

- include/builder/builder_context.h
- include/builder/dyn_var.h
- include/builder/forward_declarations.h
- samples/outputs/sample38
- samples/sample38.cpp
Currently, the only way to extend dyn_var in BuildIt to add member variables is by inheriting from dyn_var<T>. This method works for most cases, but makes it hard to refer to the inner type (for pointers and functions). 
To solve this, we now support template specialization of dyn_var<T> specifically for builder::name types and associated types. The implementation has been moved into a separate dyn_var_impl<T> type so that specializations can simply inherit from it and add members. 
This approach also allows specialization of dyn_var for pointer types allowing overloading the *, [] and -> operators to return dyn_var instead of builder and thus allowing expressions like (*a).member. 
Sample 38 has been added to demonstrate this.
> Allow template specialization as a method for extending dyn_var

- include/builder/dyn_var.h
- samples/sample33.cpp
- samples/sample38.cpp
- src/blocks/block_replacer.cpp
- src/blocks/block_visitor.cpp
Certain older versions of gcc for example gcc 5.4 that we use on the BuildIt online tool complains about some code patterns that we use. I am not entirely sure if this is because the standard isn't properly supported or we are using some non standard features. Either way, this change set correct the ones that show up every time.
> Changes to keep older versions of gcc happy

- include/builder/dyn_var.h
- src/util/tracer.cpp
- src/util/var_finder.cpp
var_finder was previously using Dl_info.dli_fbase to compute function offset which is not the right method. Use link_map.l_addr instead.
> Fixed a bug in var_finder

- include/blocks/loop_roll.h
- include/builder/builder_context.h
- include/builder/builder_dynamic.h
- include/builder/dyn_var.h
- samples/outputs.var_names/sample40
- samples/outputs/sample40
- samples/sample39.cpp
- samples/sample40.cpp
- src/blocks/loop_roll.cpp
- src/builder/builder_context.cpp
This pull request implements a new feature for generating unstructured code and a corresponding context switch. Generally when BuildIt sees a static tag it has seen before it throws a Memoization Exception. This exception is caught and the code from the other execution is copied over. This sometimes leads to blow up and in some corner cases leads to incorrect variable names (can be fixed by hoisting those variables). But this change creates a flag which when set just inserts a goto instead of trying to copy the code when a Memoization Exception is caught. The flag also disables the loop related passes.
This PR also adds sample40 which tests this feature and implements the regex compiler from the CGO2022 paper. 
Finally, this change also adds a new compile_function_with_ast function to …
> Implemented a new context flag for unstructured code generation

- include/builder/builder_dynamic.h
- samples/outputs.var_names/sample40
- samples/outputs/sample40
- src/builder/builder_context.cpp
Usually when the memoization table is updated at the end of each extraction, all the statements inside if statements are removed from the memoization table. This is because of the way we store the memoization table. It is a pointer to the parent block. 
We have to remove it because for the case of if stmts, the then/else block doesn't contain all the statements. There might be statements after the if. This is generally okay. 
But when feature_unstructured is enabled, this interferes with the optimization and a lot of code is duplicated. Fortunately, for unstructured we don't need all the statements. We just need to know the existence of the statement and the one statement. Because we are basically just inserting a goto. 
So this change, adds the sub statements inside the memoization table …
> Allow memoization table to remember statements inside sub-ifs 

- src/builder/builder.cpp
When we create return statements from function returns, we just copied over the static_offset from the expression. Unfortunately, for some reason it is hard to detect returns that are different. 
We fix this by assigning each return a different unique tag. This should be fine and not interfere with any memoization. Worst case we end up adding returns a bunch of times. 
This can be further cleaned up separately if necessary.
> Fixed return_stmt to get a different unique tag

- .github/workflows/ci-all-samples.yml
Ubuntu 22.04 uses a newer version of libdwarf which has some issues with extracting variable names. Probable cause seems to be lexical scopes. For now, we are forcing github actions to run on 20.04 and use a specific version of libdwarf.
> Forced github actions to use Ubuntu 20.04 and fixed libdwarf version

- include/builder/dyn_var.h
- include/util/var_finder.h
- src/util/var_finder.cpp
When using RECOVER_VAR_NAMES=1, the cost of looking up variable names from the dwarf info is quite high. But two variables with the same static tag will always have the same name. So we can cache names based on tags. 
This PR implements the feature and improves performance significantly.
> Added support for caching variable names based on static tags

- include/builder/array.h
- samples/outputs.var_names/sample43
- samples/outputs/sample43
- samples/sample43.cpp
This PR adds basic support for dyn_arr<T, N> which serve the purpose of dyn_arr<T>[N]. The reason these are required is so that the constructors can be called in a loop with static_var index. A normal array declaration would just produce a infinite while loop. 
The dyn_arr has its copy constructor and assignment operator deleted.
> Added basic support for dyn_arr type

- include/builder/array.h
- samples/outputs.var_names/sample43
- samples/outputs/sample43
- samples/sample43.cpp
This PR adds a copy constructor to dyn_arr that deep copy (constructs) all the internal dyn_vars. This is useful because this allows the RCE pass to eliminate these copies if necessary.
> Added a copy constructor for dyn_arr that performs a deep copy

- include/builder/block_type_extractor.h
- include/builder/dyn_var.h
- samples/sample46.cpp
This is a small change to the custom type API. The template arguments that need to be in the generated code, now need to be explicitly forwarded instead of being implicitly all generated. This allows control over which template arguments are actually for the second stage code.
> Made the template types for custom types explicit

- include/builder/dyn_var.h
- samples/sample31.cpp
- samples/sample33.cpp
- samples/sample38.cpp
- samples/sample46.cpp
When using custom_type API, as_member_of (now renamed to as_member) doesn't require the parent var pointer. The parent can be implicitly registered by constructors.
> Renamed as_member_of to as_member and removed the parent argument

- include/blocks/c_code_generator.h
- include/builder/dyn_var.h
- samples/outputs.var_names/sample46
- samples/outputs/sample46
- samples/sample46.cpp
- src/builder/builder.cpp
block::c_code_generator now has a new function generate_struct_decl that generates the definition for a custom type. Currently this only works for non-templated generated types. 
Sample 46 has been updated to demonstrate the usage.
> Added support to generate struct decls

- include/builder/static_var.h
- samples/outputs.var_names/sample47
- samples/outputs/sample47
- samples/sample47.cpp
Added a template specialization for static_var<T[]>. This would previously have to be handled by heap-allocating an array of static_vars which doesn't work well with the allocation and deletion orders. 
Sample 47 added to test it.
> Implemented basic support for arrays of static_vars

- include/blocks/block.h
- include/blocks/stmt.h
- include/blocks/sub_expr_cleanup.h
- samples/outputs.var_names/sample48
- samples/outputs/sample48
- samples/sample48.cpp
- src/blocks/sub_expr_cleanup.cpp
- src/builder/builder_context.cpp
BuildIt had a bug because of the way we erase expression statements that are part of other expressions. If there is a goto targeting these statements, the goto cannot find its target anymore. 
The solution is not immediately delete an expression statement but mark it for deletion and clean it up after the labels have been inserted. 
Sample 48 has been added to test this.
> Fixed a bug in sub expression cleanup

- include/blocks/expr.h
- include/builder/builder_base.h
- include/builder/dyn_var.h
- samples/outputs.var_names/sample30
- samples/outputs/sample30
- samples/sample30.cpp
- src/blocks/c_code_generator.cpp
Specifically added support for constructors from unsigned long long, long long and unsigned int
Modified code gen to handle generating LL as a suffix for the 64 bit constants
> Added support for more integral constructors for dyn_var and builder

- include/builder/static_var.h
- samples/sample12.cpp
BuildIt had a bug where static_var didn't have a custom copy constructor. As a result when we have code like - 
```
static_var<int> x = y;
``` 
where y is also a static_var<int>, the default copy constructor is called. This is mostly OK for copying the internal stored value, but the static_var's tracking tuple is not recorded. As a result the call to the destructor fails trying to pop the tracking tuple off the stack. 
This change adds 2 new copy constructors for static_var<T> and static_var<OT>. Consequently 2 new operator= also need to be defined, since the copy constructor is user defined. 
sample12 has been changed to test this behavior.
> Fixed bug related to missing copy constructor for static_var

- include/blocks/block_replacer.h
- include/blocks/block_visitor.h
- include/blocks/c_code_generator.h
- include/blocks/var.h
- include/builder/block_type_extractor.h
- include/builder/dyn_var.h
- include/builder/static_var.h
- samples/outputs.var_names/sample10
- samples/outputs.var_names/sample49
- samples/outputs/sample10
- samples/outputs/sample49
- samples/sample49.cpp
- src/blocks/block_replacer.cpp
- src/blocks/block_visitor.cpp
- src/blocks/c_code_generator.cpp
- src/blocks/var.cpp
- src/blocks/var_namer.cpp
This change adds two features - 
1. Support for reference types - dyn_var<T&>. Very similar in implementation to pointer type. builder::block_type_extractor specialization has been added to create these types. Sample 10 updated to test this
2. Support for creating named variables with declaration. The builder::with_name helper now has an extra boolean parameter (defaulted to false) to also emit a declaration. This allows creating local variables with exact names. 
Both these features are required by the FPGA util library and backen.
> Added support for reference types and creating named variables with decl

- include/blocks/label_inserter.h
- samples/outputs.var_names/sample50
- samples/outputs/sample50
- samples/sample50.cpp
- src/blocks/label_inserter.cpp
- src/builder/builder_context.cpp
Fixes #53 
The bug in the referenced issue was because of jumps and jump targets being duplicated across branches due to "failure to merge". This causes the jump to target a label that is in a different branch messing up the loop_finder invariant. 
We fixed this by inserting labels at all possible jump targets for a particular static label. We then maintain the current label from the stmt block and update it when we visit a new one. This way a goto stmt always sees a structured label. 
Sample 50 has been added to test the same.
> Fixed the bug with labels not being duplicated across branches

- .github/workflows/ci-all-samples.yml
- include/builder/lib/utils.h
- samples/outputs.var_names/sample40
- samples/outputs.var_names/sample52
- samples/outputs/sample
- samples/outputs/sample40
- samples/outputs/sample52
- samples/sample52.cpp
- src/builder/builder_context.cpp
- src/builder/builder_dynamic.cpp
Allow converting ifs like 
```
if (foo) {
bar();
return x;
else {
baz();
}
```
into 
```
if (foo) {
bar();
return x;
}
baz();
```
Sample 52 tests this. 
Minor change: Changed order or operands in the comparison in up_cast_range.
> Allow flattening ifs when a branch ends in return

- include/builder/dyn_var.h
- samples/outputs.var_names/sample53
- samples/outputs/sample53
- samples/sample53.cpp
Usually when dyn_var are instantiated, they are immediately initialized. This means they can be declared only inside builder contexts (or should use as_global or with_name). 
This is restrictive when the user wants to create objects outside the context that have dyn_var members. Currently this requires the user to push the creation of the entire object inside the context. It creates issues with expensive computations being run multiple times. To get around this, we add a new constructor helper `builder::defer_init` and a member function `deferred_init`. 
The constructor helper allows declaring dyn_var(s) without actually doing anything. The member function `deferred_init`, then does the job of the constructor and should be called inside the context. 
Added sample53 to demonstrate/test …
> Added support for defer init for dyn_var

- include/blocks/block.h
- include/blocks/var_namer.h
- samples/outputs.var_names/sample54
- samples/outputs/sample54
- samples/sample54.cpp
- src/blocks/loop_finder.cpp
- src/blocks/var_namer.cpp
This is small change to var hoister to take care of changing types of reference types when hoisting. This wasn't required before because we didn't have reference types. 
Also fixes a small bug in loop_finder when dealing with 2 labels with the same static tags. 
sample54 updated to check for reference types.
> Fixed var hoister to convert reference types to pointer types when hoisting

- .gitmodules
- Makefile
- include/blocks/c_code_generator.h
- include/builder/builder_context.h
- include/builder/static_var.h
- include/util/tracer.h
- make/buildit_rules.mk
- make/deps.mk
- make/dirs.mk
- make/format.mk
- make/setvars.mk
- src/blocks/c_code_generator.cpp
- src/builder/builder_context.cpp
- src/util/tracer.cpp
This commit adds a new build flag - ENABLE_D2X. This flag should only be enabled when the submodule deps/d2x is fetched. Enabling this flag builds BuildIt with [D2X](https://buildit.so/d2x) support. D2X is automatically built and linked. 
Just enabling this feature does not change any behavior. To actually use these features, the user can set the `enable_d2x` member in builder_context and use the c_code_generator::generate_code_d2x function instead of the usual c_code_generator::generate_code function. Both functions the same interface. This will dump all the D2X debugging information with the generated code. 
Generated code must be linked with the D2X runtime libraries.
> Added support for D2X debugging

- include/builder/builder_context.h
- include/builder/dyn_var.h
- include/builder/forward_declarations.h
- include/builder/static_var.h
- samples/outputs.var_names/sample53
- samples/outputs/sample53
- samples/sample53.cpp
- src/builder/builder_context.cpp
- src/util/tracer.cpp
This change adds support for deferring inits for static_var with builder::defer_init same as dyn_var. Deferred static vars are added to a separate deferred_static_var_tuples in the builder_context and currently are never removed. 
We can add an option to uninit static vars in the future. Sample53 has been updated to test this.
> Added support for deferred init static vars

- include/builder/builder_base.h
- include/builder/dyn_var.h
- include/builder/forward_declarations.h
- samples/outputs.var_names/sample46
- samples/outputs/sample46
- samples/sample38.cpp
- samples/sample46.cpp
Previously all dyn_var returned a plain old builder for the *, [] operators. But this makes accessing members from custom types difficulty.
We have now changed the specialization for all pointer types T* to return a dyn_var<T> with the expression inside for * and []. Further more we add an implementation of -> for these types similar to how it was implemented in sample38
sample38 has been updated to not require a separate specialization for dyn_var<foo_t*> anymore. sample46 also has been updated to test the new feature.
> Changed dyn_var specialization for pointer types to return the appropriate type

- include/builder/builder.h
- include/builder/builder_base.h
- include/builder/builder_context.h
- include/builder/dyn_var.h
- include/builder/forward_declarations.h
- include/builder/operator_overload.h
- include/builder/signature_extract.h
- src/builder/builder.cpp
This commit simplifies the implementation of the dyn_var (dyn_var_impl) by merging trivial constructors (that defer to builder), operators with templated versions. We also remove unused constructor helpers like dyn_var_sentinel_type. 
No change in functionality or new samples
> Cleanup dyn_var helper types, constructors and operators

- include/blocks/basic_blocks.h
- include/builder/builder_context.h
- src/blocks/basic_blocks.cpp
- src/builder/builder_context.cpp
This patch adds a basic_block class and a function to translate the AST to a CFG representation. It also dumps the basic block to std::cerr in builder_context.cpp for debugging
The algorithm to convert the AST to CFG uses a worklist to do so, it first creates basic blocks for all the top level AST elements, and then using a worklist iteratively expands these top level AST elements, adding more basic blocks between them.
bb1 ---> bb2 ==> bb1 ---> (bb-a1...bb-an) ---> bb2
It also pads if statement blocks with an exit blocks. This makes it easier to handle loops, as we now have a single entry/exit into the if block.
|----<then_block>----|
<if_block>----|                    |----<exit_block>
|----<else_block>----|
* buildit input source code dyn_var<int> a = 0;
for (dyn_var<int> c = 0; c < …
> [blocks] Add basic blocks for CFG representation of the AST

- include/util/var_finder.h
- samples/outputs.var_names/sample55
- samples/outputs/sample55
- samples/sample55.cpp
- src/util/var_finder.cpp
This change only affects the configuration RECOVER_VAR_NAMES=1 (and ENABLE_D2X). Previously when dyn_vars are declared inside structs, they won't get a name because the address doesn't match with the parent object. This change also looks for members of structs that are in scope and checks if any member is at the right offset. 
This should also improve the static var names extraction in ENABLE_D2X. 
Sample55 has been added to test this.
> added support for extracting member names with RECOVER_VAR_NAMES=1

- include/builder/block_type_extractor.h
- include/builder/dyn_var.h
- samples/outputs.var_names/sample56
- samples/outputs/sample56
- samples/sample56.cpp
- src/builder/block_type_extractor.cpp
This change further simplifies custom types in 2 ways - 
1. Custom types are no longer _required_ to inherit from builder::custom_type, although they can choose to do so for appending template args to names. Custom types are also not required to define the `type_name` member. If they don't, an automatically generated name will be assigned. This can be used in combination with c_code_generator::generate_struct_decl to create custom types. 
2. Members are no longer required to use member_of, although they can use it if members are created outside the constructor itself or if they are using specialization for dyn_var. Instead they can simply with with_name to name the members or leave the member uninitialized in which case it is assigned a generated name. This can be again used in …
> Simplified API for custom types (yet again)

- include/blocks/var.h
- include/builder/block_type_extractor.h
- include/builder/builder_base.h
- samples/outputs.var_names/sample30
- samples/outputs/sample30
- samples/sample30.cpp
- src/blocks/c_code_generator.cpp
Added support for const and volatile qualified types and added explicit buildit constructor for long like long long. 
Updated sample30 to test this.
> Added support for types to be const and volatile qualified

- include/builder/dyn_var.h
- samples/outputs.var_names/sample38
- samples/outputs/sample38
- samples/sample38.cpp
A recent change (#65) simplified the implementation of pointer types esp. struct types so that the overloaded * and [] operators returned dyn_var<T> instead of builder. This allowed accessing members from these easier. However this causes a major bug where if the user writes code snippets like - 
```
dyn_var<T*> ptr;
dyn_var<T> a = ptr[i];
```
the copy a is completely removed. This is because the operators construct the returned object using (builder::cast). Due to copy elision, a itself is constructed with (cast) causing errors. If a is used multiple times, each use will have ptr[i]. Bugs arise when ptr[i] has side effects. 
This bug was discovered while implementing a toy language interpreter with @tekknolagi 
To fix this issue, we introduce a clone of dyn_var called dyn_var_mimic which …
> Fixed bug in dyn_var implementation where returns from [] and * cause bug

- include/blocks/block_replacer.h
- include/blocks/block_visitor.h
- include/blocks/c_code_generator.h
- include/blocks/expr.h
- include/builder/operator_overload.h
- src/blocks/block_replacer.cpp
- src/blocks/block_visitor.cpp
- src/blocks/c_code_generator.cpp
- src/blocks/expr.cpp
The PR merged before this reminded me I had implemented support for the unary minus operator as well for my work. Let me know if something seems awry!
> Added support for unary minus operator

- include/blocks/var.h
- include/builder/block_type_extractor.h
- samples/outputs.var_names/sample30
- samples/outputs/sample30
- samples/sample30.cpp
- src/blocks/c_code_generator.cpp
- src/blocks/var.cpp
Basic support for new scalar type bool. Builder constructors haven't been changed, so constants of type bool should simply turn into integers. 
Sample 30 updated.
> Added support for bool type

- include/blocks/block.h
- include/blocks/expr.h
- include/blocks/stmt.h
- include/blocks/var.h
- src/builder/builder_context.cpp
This PR merges a big change. Motivated from some of the bugs uncovered from the fuzzer. Following changes are added - 
1. Adds a clone implementation to all AST nodes. 
2. Immediately post extraction, the entire tree is duplicated. This way none of the nodes (except for vars and labels) are never shared, making the tree an actual AST and not AS-DAG. 
This change helps improve #54 where gotos were not duplicated.
> Blocks AST cloning

- include/builder/array.h
- samples/outputs.var_names/sample43
- samples/outputs/sample43
- samples/sample43.cpp
This change set simply changes the array type to not be specialized for dyn_vars and makes them a general array type that have static loops for construction and destruction. This way we can now throw in types that contain dyn_vars instead of being dyn_vars themselves. A type alias dyn_arr is created for backwards compatibility.
Sample43 has been updated to test the new feature.
> Extended builder::arrays to support any types and not just dyn_vars

- include/builder/static_var.h
- samples/outputs.var_names/sample58
- samples/outputs/sample58
- samples/sample58.cpp
This changeset relaxes the big constraint on static_vars having to be destroyed in the exact same order as they are initialized. This was previously asserted in the destructor. However this makes returning static_vars from functions difficult due to copy elision. This change relaxes this now by simply setting the size of the variable in the tracking tuple to be 0. tracking tuples of size 0 are cleaned up lazily.
This also doesn't require us to remove the element from the middle which _could_ mess with static_tag comparisons. 
Sample58 has been added to test this. 
This should also help with #76
> Support out of order destruction of static_vars

- include/builder/block_type_extractor.h
- samples/outputs.var_names/sample56
- samples/outputs/sample56
- samples/sample56.cpp
There was a bug with BuildIt and unnamed custom structs with global variables. 
Unnamed structs grab their names using the type_namer trait. This trait uses a static variable to keep track of types that already have a named assigned. However, we were using std::string to hold this name. It is possible that a global constructor could request a name but the static member hasn't been initialized yet. This reads an unconstructed std::string which invokes undefined behavior. 
To fix this we make member to be a std::string* instead of std::string. 
sample56 has been updated to test this.
> Fixed issue with custom_struct global constructors

- include/builder/block_type_extractor.h
- include/builder/dyn_var.h
- include/builder/forward_declarations.h
- samples/outputs.var_names/sample59
- samples/outputs/sample59
- samples/sample59.cpp
When dyn_var<> is wrapped around a custom type, the operator[] behaves like a usual type and returns generic builder. This doesn't allow accessing members from the return value (a very common requirement in custom vector implementations). 
This change allows custom types to optionally specify a `dereference_type` typedef. If defined the return type of operator[] is set accordingly and the operator returns an object of type `dyn_var_mimic<T::dereference_type>` (just like dyn_vars of pointers). 
sample59 has been added to test this.
> Allow custom types to specify a dereference_type for operator[]

- .github/workflows/ci-all-samples.yml
- include/builder/dyn_var.h
- src/builder/builder.cpp
- src/builder/builder_context.cpp
BuildIt had a major bug with the implementation of custom structs. BuildIt uses a parents_stack to keep track of dyn_var objects being constructed so nested objects can find existence (and pointers) of their parents. 
There was a bug where the parents_stack was declared static in the header. This would generally be okay because the stack is pushed/popped from member_begin<T> and member_end calls to which should be in the same translation unit. However since member_begin is templated there are many instances of it (potentially in different translation units) but just one member_end. This means these two could point to different instances of the stack. This leads to a problem with more pops on a vector than pushes which is undefined behavior. 
To solve this, parents_stack has been made a …
> Fixed bug with parents_stack being static

- include/blocks/generic_checker.h
- include/blocks/var.h
- include/builder/block_type_extractor.h
- include/builder/dyn_var.h
- include/builder/generics.h
- samples/outputs.var_names/sample60
- samples/outputs/sample60
- samples/sample60.cpp
- src/blocks/generic_checker.cpp
- src/builder/builder_context.cpp
- src/builder/generics.cpp
This change set introduces the dyn_var<generic> type. This type doesn't have type when created but can be assigned one through the execution of first stage logic. This allows writing generic code that generates code with different types. This also allows computing array and template sizes through first stage code. 
The new builder::type opaque type has been introduced that holds runtime type values. These type provides helper functions to operate on types like pointer_of, array_of etc. 
Sample 60 has been added to test this basic change.
> Add basic support for generics

- include/blocks/block_replacer.h
- include/blocks/expr.h
- include/blocks/matchers/matchers.h
- include/blocks/matchers/patterns.h
- include/blocks/matchers/replacers.h
- include/builder/builder_context.h
- include/builder/exceptions.h
- include/builder/forward_declarations.h
- include/builder/nd_var.h
- include/builder/static_var.h
- make/dirs.mk
- samples/outputs.var_names/sample61
- samples/outputs.var_names/sample62
- samples/outputs/sample61
- samples/outputs/sample62
- samples/sample61.cpp
- samples/sample62.cpp
- src/blocks/matchers.cpp
- src/blocks/replacers.cpp
- src/builder/builder_context.cpp
This changeset adds two new features - 
1. Added basic support for nd_vars<T> a new type for sampling and constraining non-deterministic values. The use case is for implementing backward data-flow analyses. Currently support for nd_vars<bool> has been added. bool supports a basic requires_equal function. Sample 61 has been added to test the same. 
2. Merged support for pattern matches: A new type matcher::pattern has been introduced that allows expressing patterns with arbitrary level of abstraction. Two interfaces for matchers and replacers have been introduced. patterns support captures of named expressions and common overloads for simplifying pattern creation. Support for statement matching will be added later. Sample 62 has been added to test the same.
> Add support for nd_vars and Merge pattern matchers

- include/builder/dyn_var.h
- samples/outputs.var_names/sample63
- samples/outputs/sample63
- samples/sample63.cpp
BuildIt had a bug with how it handles dyn_var<T*> for recursive types. A very common pattern like the following appears in linked list implementations - 
```
struct linked_list {
dyn_var<linked_list*> next;
};
```
Typically declaring a pointer to a type doesn't require the type to be "complete". However the way dyn_var<T*> is implemented is it tries to create an object of type dyn_var<T> inside to return when the ->/[] operator is called. Now this causes issues because dyn_var<T> requires T to be "complete" since it inherits from T when T is a struct type. 
This causes the above sample to fail with compile error. 
To fix this we make the extra member of type dyn_var<T> inside dyn_var<T*> be created lazily. We change the member to be of type std::unique_ptr<dyn_var<T>> and allocate it when …
> Fixed bug with dyn_var<T*> requiring T to be completely defined

- include/builder/block_type_extractor.h
- include/builder/dyn_var.h
- samples/outputs.var_names/sample63
- samples/outputs/sample63
- samples/sample63.cpp
BuildIt had an issue where incomplete types cannot be given names without completing them. Ideally users shouldn't use incomplete types in BuildIt code bases, however when migrating C code containing stdio.h headers this seems to be a recurring theme. 
So we are now supporting _yet another way to name_ struct types using the type trait external_type_namer. 
Sample63 has been udpated to test the same.
> Added support for external type namers

- include/builder/builder_context.h
Added `#include <cstdint>` to builder_context.h to fix the following compile error:
```
CXX    annotate.o
In file included from /home/chillenb/src/buildit/include/builder/builder_base.h:8,
from /home/chillenb/src/buildit/include/builder/builder.h:3,
from /home/chillenb/src/buildit/src/builder/annotate.cpp:1:
/home/chillenb/src/buildit/include/builder/builder_context.h:25:9: error: ‘uint32_t’ does not name a type
25 |         uint32_t size;
|         ^~~~~~~~
/home/chillenb/src/buildit/include/builder/builder_context.h:11:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
10 | #include <unordered_set>
+++ |+#include <cstdint>
11 | #include <vector>
```
> make sure uint32_t is defined

- include/blocks/label_inserter.h
- include/blocks/var_namer.h
- include/builder/block_type_extractor.h
- include/builder/builder_context.h
- include/builder/dyn_var.h
- include/builder/forward_declarations.h
- include/builder/nd_var.h
- include/builder/static_var.h
- include/builder/var_snapshots.h
- include/util/hash_utils.h
- include/util/mtp_utils.h
- include/util/tracer.h
- include/util/var_finder.h
- samples/outputs.var_names/sample65
- samples/outputs/sample65
- samples/sample65.cpp
- src/blocks/label_inserter.cpp
- src/blocks/var_namer.cpp
- src/builder/builder.cpp
- src/builder/builder_context.cpp
- src/util/tracer.cpp
- src/util/var_finder.cpp
This change set adds a major feature which allows wrapping static_var around arbitrary types that have a copy constructor and == defined. This is required for wrapping STL types like vectors and maps into static_var. 
With this, we also deprecate using tag.stringify() as a unique representation of tag since some types cannot be stringified. All (unordered) maps and sets now directly use tag as an index. To support this a std::hash implementation has been added for tags. The objects that cannot be hashed are not included in the hash, which could also collisions, but that is okay since hashes are expected to be completely unique, the == operator does handle correctness. 
The hash implementation caches hashes as much as possible to avoid overheads and virtual dispatches. Finally, the …
> Support for general types inside static_var
